import localFont from "next/font/local";
import "./globals.css";
import {Noto_Sans} from 'next/font/google'

const zen=Noto_Sans({
  subsets:['cyrillic','latin'],
  weight:['300','400','500','600','700'],
  display:'swap',
  variable:'--font-zen',
  style:['normal']
})
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={zen.className} >
<div style={{height:'110px',weight:'auto',backgroundColor:'red'}}>Руперт</div>

        {children}
      </body>
    </html>
  );
}
