import localFont from "next/font/local";
import "./globals.css";
import { Noto_Sans } from 'next/font/google'
  import Link from "next/link";
import style from '../css/main.module.css'
const zen = Noto_Sans({
  subsets: ['cyrillic', 'latin'],
  weight: ['300', '400', '500', '600', '700'],
  display: 'swap',
  variable: '--font-zen',
  style: ['normal']
})
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={zen.className} style={{ height: '50px', weight: 'auto', backgroundColor: '' }} >
        <div style={{padding:'15px'}} >    
          <center>      
            <Link className={style.main} href={'abaut'}>Главная</Link>
            <Link className={style.main} href={'/main/god'}>Пица</Link>
            <Link className={style.main} href={'/main/swing'}>Кухня фри</Link>
            <Link className={style.main} href={'/main/fetch'}>Суши</Link>
            <Link className={style.main} href={'/statics'}>Обеды</Link>
            </center>
        </div>

        {children}
      </body>
    </html>
  );
}
